apiVersion: v1
data:
  ### Aqua enforcer token input needed - Base64 encoded ###
  token: "MGY3OGM1M2MtNTgzMy00YWJhLWJmNDYtZGI1NWM3NmZkZTRh"
kind: Secret
metadata:
  annotations:
    description: Aqua Enforcer token secret
  labels:
    deployedby: aqua-yaml
  name: enforcer-token
  namespace: aqua
type: Opaque
