apiVersion: v1
kind: Secret
metadata:
  annotations:
    description: Aqua Scanner username and password
  labels:
    deployedby: aqua-yaml
  name: aqua-scanner
  namespace: aqua
type: Opaque
data:
  # Aqua Scanner Username - Base64 Encoded
  AQUA_SCANNER_USERNAME: "YXF1YS1zY2FubmVyCg=="
  # Aqua Scanner Password - Base64 Encoded
  AQUA_SCANNER_PASSWORD: "UGFzc3dvcmQxMjMhCg=="
  # Base64 Encoded - Aqua web root cert
  aqua-web-root-cert: ""
  
